version: '3'
services:
    portfilio:
        container_name: phuriq_portfilio
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - '3000:3000'
        restart: unless-stopped